### ISSUE TITLE
Add link to solution of "Operation not permitted" exception

### ISSUE THREAD

**Issue by nevmerzhitsky** [steffengy/node-raw-socket#10]
Hi, Steffen!

You can add link to http://blog.fpmurphy.com/2009/05/linux-security-capabilities.html article to the second paragraph of https://github.com/steffengy/node-raw-socket#raw-socket-behaviour to help your users solve this issue without taking superuser privileges. Or copy my own instruction about this https://github.com/nevmerzhitsky/node-ping-scheduler#troubleshooting.

**Comment by steffengy** [comment]
using this fork is highly discouraged as mentioned in the description,
since the original source has caught up and is now in comparison to this still maintained.
